// procedure declaration
BEGIN SANITIZE
  TEMPERATURE 215F
  HUMIDITY     95%
  WAIT         30 MINUTES

  FAN          ON
  WAIT          5 MINUTES
END SANITIZE

// procedure call
SANITIZE

// bounded loop
BEGIN LOOP 3
  TEMPERATURE 80C
  HUMIDITY    45%
  WAIT        10 MINUTES
      
  TEMPERATURE 90C
  WAIT        10 MINUTES
END LOOP

TEMPERATURE 75C
HUMIDITY    30%
WAIT         5 MINUTES